image: docker:git

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: registry.gitlab.com/eggrollington/$CI_PROJECT_NAME

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
  - build and stage

job 1:
  stage: build and stage
  script:
   - docker build -t $CONTAINER_IMAGE:$CI_COMMIT_SHA .
   - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA